# Generated by Django 4.2 on 2023-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_editor', '0002_sqlquery_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_text', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SQLQuery',
        ),
    ]
